services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NUGET_PACKAGES=/app/nuget-packages
    ports:
      - "5000:80"
    volumes:
      - sqlite-data:/app/data
      - nuget-packages:/app/nuget-packages
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/Events.db
      - DOTNET_RUNNING_IN_CONTAINER=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

volumes:
  sqlite-data:
    driver: local
  nuget-packages:
    driver: local 